export const SET_LANGUAGE = 'SET_LANGUAGE'
export const FILTERED_PRODUCTS = 'FILTERED_PRODUCTS'

//Fetch Data
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const FETCH_SUB_CATEGORIES_REQUEST = 'FETCH_SUB_CATEGORIES_REQUEST'
export const FETCH_SUB_CATEGORIES_SUCCESS = 'FETCH_SUB_CATEGORIES_SUCCESS'
export const FETCH_SUB_CATEGORIES_FAILURE = 'FETCH_SUB_CATEGORIES_FAILURE'
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
// Filters
export const ADD_TYPE = 'ADD_TYPE'
export const REMOVE_TYPE = 'REMOVE_TYPE'
export const SET_SORT = 'SET_SORT'

// UI

export const SHOW_ALERT = 'SHOW_ALERT'